name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you are using

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install  # Adjust based on your project setup

      - name: Build the project
        run: npm run build  # Adjust based on your project setup

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          # Specify the folder containing static files for GitHub Pages to deploy
          # Usually, it's the "dist" folder or "build" folder depending on your build tool
          folder: 'build'
